### ISSUE TITLE
I am getting React/RCTView.h' file not found error

### ISSUE THREAD

**Issue by afomic** [Anyline/react-native-image-to-pdf#17]
When I tried building the ios application I am getting this error

React/RCTView.h' file not found

The android application works fine though.

expo kit detached project, I have tried using react-native link and manual install

**Comment by JonasLaux** [comment]
Are you using podfiles? This is normally a problem with react itself

**Comment by afomic** [comment]
yes, i am

**Comment by JonasLaux** [comment]
Can you please try this in your Podfile?

https://github.com/react-native-community/react-native-linear-gradient/issues/165#issuecomment-454988844

Here is our Podfile from our React-Native Example app. We also had the same problem at some point. I don't know what exactly the solution was, but you have to add something to your podfile. But as mentioned, this shouldn't occur because of this Plugin.

https://github.com/Anyline/anyline-ocr-react-native-module/blob/master/example/RNExampleApp/ios/Podfile

**Comment by tattivitorino** [comment]
@afomic were you able to fix this? I have an expo detached app as well, ad my pod file is as follows, but honestly I am a bit "scared" of messing with it according to the solutions presented by @JonasLaux 
any help will be appreciated
cheers

```
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'

target 'my-app' do
  pod 'ExpoKit',
    :git => "http://github.com/expo/expo.git",
    :tag => "ios/2.11.2",
    :subspecs => [
      "Core"
    ],
    :inhibit_warnings => true

  # Install unimodules
  require_relative '../node_modules/react-native-unimodules/cocoapods.rb'
  use_unimodules!(
    modules_paths: ['../node_modules'],
    exclude: [
      'expo-face-detector',
      'expo-payments-stripe',
    ],
  )

  pod 'React',
    :path => "../node_modules/react-native",
    :inhibit_warnings => true,
    :subspecs => [
      "Core",
      "ART",
      "RCTActionSheet",
      "RCTAnimation",
      "RCTCameraRoll",
      "RCTGeolocation",
      "RCTImage",
      "RCTLinkingIOS",
      "RCTNetwork",
      "RCTSettings",
      "RCTText",
      "RCTVibration",
      "RCTWebSocket",
      "DevSupport",
      "CxxBridge"
    ]
  pod 'yoga',
    :path => "../node_modules/react-native/ReactCommon/yoga",
    :inhibit_warnings => true
  pod 'DoubleConversion',
    :podspec => "../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec",
    :inhibit_warnings => true
  pod 'Folly',
    :podspec => "../node_modules/react-native/third-party-podspecs/Folly.podspec",
    :inhibit_warnings => true
  pod 'glog',
    :podspec => "../node_modules/react-native/third-party-podspecs/glog.podspec",
    :inhibit_warnings => true

  pod 'RNImageCropPicker', :path => "../node_modules/react-native-image-crop-picker"

  pod 'RNFS', :path => '../node_modules/react-native-fs'

  pod 'react-native-document-picker', :path => '../node_modules/react-native-document-picker'

  pod 'RNInAppBrowser', :path => '../node_modules/react-native-inappbrowser-reborn'

  post_install do |installer|
    installer.pods_project.main_group.tab_width = '2';
    installer.pods_project.main_group.indent_width = '2';

    installer.target_installation_results.pod_target_installation_results
      .each do |pod_name, target_installation_result|

      if pod_name == 'ExpoKit'
        target_installation_result.native_target.build_configurations.each do |config|
          config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)']
          config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] << 'EX_DETACHED=1'
          
          # Enable Google Maps support
          config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] << 'HAVE_GOOGLE_MAPS=1'
          config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] << 'HAVE_GOOGLE_MAPS_UTILS=1'
          
        end
      end


      if ['Amplitude-iOS','Analytics','AppAuth','Branch','CocoaLumberjack','FBSDKCoreKit','FBSDKLoginKit','FBSDKShareKit','GPUImage','JKBigInteger2'].include? pod_name
      target_installation_result.native_target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '10.0'
      end
      end

      # Can't specify this in the React podspec because we need to use those podspecs for detached
      # projects which don't reference ExponentCPP.
      if pod_name.start_with?('React')
        target_installation_result.native_target.build_configurations.each do |config|
          config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '10.0'
          config.build_settings['HEADER_SEARCH_PATHS'] ||= ['$(inherited)']
        end
      end

      # Build React Native with RCT_DEV enabled and RCT_ENABLE_INSPECTOR and
      # RCT_ENABLE_PACKAGER_CONNECTION disabled
      next unless pod_name == 'React'
      target_installation_result.native_target.build_configurations.each do |config|
        config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)']
        config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] << 'RCT_DEV=1'
        config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] << 'RCT_ENABLE_INSPECTOR=0'
        config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] << 'ENABLE_PACKAGER_CONNECTION=0'
      end

    end
  end
end

```

**Comment by visw227** [comment]
this issue still exists. Any idea fixing it?

**Comment by JonasLaux** [comment]
React changed their namespaces some time ago. So if you got this error, as i understand it correctly, you have linked React multiple times in your project. 
Here https://github.com/react-native-community/react-native-maps/issues/2324 are some solutions how you can identify your problem.

**Comment by visw227** [comment]
It didnot help. I'm getting this error when i manually link for react-native 0.60 ... If I don't manually link, then getting undefined error for RNImagetopdf

**Comment by JonasLaux** [comment]
also if you adjust your podfile?

**Comment by d-vincent** [comment]
Hey fellas, I ran into this issue and here is how I fixed it. 
Unlinked react-native-image-to-pdf
Removed pods folder and podfile from project
Re-linked with react-native link react-native-image-to-pdf
Returned podfile
pod install.

For some reason, the link command was not working properly when there was a podfile/pods folder present in the project

**Comment by JonasLaux** [comment]
Thanks for the Workaround. I will close this issue for now. If this issue still persist, feel free to reopen it again.

**Comment by Nirmit04** [comment]
Tried all the methods mentioned , still facing the same issue @JonasLaux
